language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

jobs:
  include:
    - stage: build
      script: ./gradlew build -s
    - state: test
      script: ./gradlew allTests
    - state: dokka
      script: ./gradlew dokkaHtml
