[versions]

kt = "1.8.22"
kt-serialization = "1.5.1"
kt-coroutines = "1.7.2"

microutils = "0.19.7"
tgbotapi = "9.0.0"
kslog = "1.1.1"

jb-exposed = "0.41.1"
jb-dokka = "1.8.20"

sqlite = "3.42.0.0"

klock = "4.0.3"
uuid = "0.7.1"

ktor = "2.3.2"

gh-release = "2.4.1"

koin = "3.4.2"

[libraries]

kt-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kt" }

kt-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kt-coroutines" }
kt-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kt-serialization" }

tgbotapi = { module = "dev.inmo:tgbotapi", version.ref = "tgbotapi" }
tgbotapi-behaviourBuilder-fsm = { module = "dev.inmo:tgbotapi.behaviour_builder.fsm", version.ref = "tgbotapi" }
microutils-repos-exposed = { module = "dev.inmo:micro_utils.repos.exposed", version.ref = "microutils" }
kslog = { module = "dev.inmo:kslog", version.ref = "kslog" }

koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }

jb-exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "jb-exposed" }

sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }


kt-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kt" }


buildscript-kt-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kt" }
buildscript-kt-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kt" }
buildscript-jb-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "jb-dokka" }
buildscript-gh-release = { module = "com.github.breadmoirai:github-release", version.ref = "gh-release" }
